### ISSUE TITLE
Review March 18

### ISSUE THREAD

**Issue by iamciera** [cabinetofcuriosity/idigbio_explore#2]
### Part 1

- [ ] Looks good. We should maybe build into one of the other posts....
- [ ] Contact Kevin and Deb about iDigBio tutorial.  Have them review it. Are there tutorials somewhere?

## Part 2
- [ ] I think we should make the "bears" images are a bit too much. I like how it is tounge and cheek, but I think it will look unweildy in the actual post. 
- [ ] Are we using the iDigBio for all the map features?
 - [ ] I think part 1 and part 2 can be just a brief tutorial that functions as a intro to what you can do with the idigbio package.  We should combine them.  Thoughts?

 ## Part 3

Overall this is beautiful.  Great Job! 

 - [ ] Why do you love cephalopods?  
 - [ ] Why did you also get the fossils dataset in the begining?  They kind of just show up. 
 - [ ] I love the geopandas map. But I think the fossils dataset is a little weird to include. Muddles the story. I think you should just stick to the cephlapods.
